name: Ticket
description: Get help debugging something Umi-related
body:
- type: input
  attributes:
    label: Umi version
- type: textarea
  attributes:
    label: Description
    description: Briefly describe your issue and/or paste a code snippet that gives enough context
    value: |
        ```ts
        // Paste the relevant snippet of code...
        ```
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Error
    description: When applicable, paste the relevant part of your error message
    value: |
        ```
        // Paste your error message here...
        ```
    render: markdown
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
