name: Ticket
description: Get help debugging something Umi-related
body:
- type: input
  attributes:
    label: Umi version
- type: textarea
  attributes:
    label: Code
    description: Paste a code snippet that gives enough context. Use comments for additional info.
    value: |
        Paste the relevant snippet of TypeScript code...
    render: ts
  validations:
    required: true
- type: textarea
  attributes:
    label: Error
    description: When applicable, paste the relevant part of your error message
    value: |
        Paste your error message here...
    render: text
