name: Ticket
description: Get help debugging something Umi-related
body:
- type: input
  attributes:
    label: Umi version
- type: markdown
  attributes:
    label: Description
    description: Briefly describe your issue and/or paste a code snippet that gives enough context
    value: |
        ```ts
        // Paste the relevant snippet of code...
        ```
  validations:
    required: true
- type: markdown
  attributes:
    label: Error
    description: When applicable, paste the relevant part of your error message
    value: |
        ```
        // Paste your error message here...
        ```
